### PR TITLE
Bugfix: add missing code west-taiwan

### PR DESCRIPTION
**Pull request by mingtsay**
Due to the lack of the important code for the CN flag, I add the missing code for it.

### CODE REVIEW

**Comment by YamiOdymel** [comment]
這個小小的舉動將改動我的人生

**Comment by mingtsay** [comment]
Force pushed to catch up the latest code in tocas4 branch.
It is ready to merge again. 😄

**Comment by mingtsay** [comment]
Force pushed to catch up the latest code in tocas4 branch.
It is ready to merge again. 😄

**Comment by mingtsay** [comment]
Force pushed to catch up the latest code in tocas4 branch.
It is ready to merge again. 😄

**Pull request closed without merging**
